### PR TITLE
Fix SEGFAULT at terminal resize

### LINKED ISSUE #220: Crush when resize terminal
**Problem Description:**
I'm encountering an issue while using the Pktgen-DPDK tool. When I attempt to resize the terminal command line during execution, the Pktgen program crashes.

**Steps to Reproduce:**
1. Open a terminal and launch Pktgen-DPDK.
2. Try resizing the terminal window (e.g., adjusting the width or height).
3. Observe if Pktgen crashes.

**Expected Behavior:**
Pktgen should run smoothly without crashing when resizing the terminal window.

**Actual Behavior:**
Pktgen crashes when resizing the terminal window and displays an error message.

**Additional Information:**
- Pktgen-DPDK Version: DPDK 23.7.0, Pktgen 23.06.1(newest commit)

I've checked the Pktgen-DPDK GitHub repository, and I couldn't find a similar issue reported. I hope to receive assistance in resolving this problem. Thank you!

### PR DESCRIPTION
**Pull request by Phikimon**
this_cli is a thread-local variable used by functions within SIGWINCH signal handler. This means that it can only be accessed by the main thread (that created it). Previosly however this signal could be handled by any thread of the process, thus occasionally causing SEGFAULTs.
In a multithreaded process if a signal is blocked by all threads but one, then the signal will be delivered to the thread expecting it. Using the fact that signal masks are inherited by pthreads this commit blocks SIGWINCH in the beginning of main(before the workers and the screen timer are spawned) and unblocks it just before cli_start(). 
The unblocking could be moved to scrn_start() function. 
An alternative to this could be adding a 'handle_winch' atomic to struct cli_scrn.

Fixes #220

### CODE REVIEW

**Review by KeithWiles — APPROVED** [review]
Thank you.

File: app/pktgen-main.c [hunk 1]
```diff
@@ -561,6 +574,13 @@ main(int argc, char **argv)
     }
 
     pktgen_log_info("=== Run CLI\n");
+
+    /* Unblock SIGWINCH so main thread
+     * can handle screen resizes */
+    sigemptyset(&set);
+    sigaddset(&set, SIGWINCH);
+    pthread_sigmask(SIG_BLOCK, &set, NULL);
```
Comment (KeithWiles) [inline app/pktgen-main.c]: I just noticed this code looks exactly like the code at line 440, but this one states unblock and the other states block. Should line 582 use SIG_UNBLOCK instead?

Comment (Phikimon) [reply app/pktgen-main.c]: Indeed, thank you.

**Comment by Phikimon** [comment]
Corrected the typo.

**Review by KeithWiles — APPROVED** [review]
Thank you.
